### PR TITLE
Set max networkx, numpy, and scipy versions

### LINKED ISSUE #28: Incompatibility with NetworkX version 2
`networkx>=1.4` from `requirements.txt` installs `networkx==2.1` as NetworkX was upgraded to 2.1 recently and I had the following error in a Docker image with `ubuntu:14.04` base image.

```
Traceback (most recent call last):
  File "/opt/OmicsIntegrator-0.3.1/scripts/forest.py", line 1464, in <module>
    main()
  File "/opt/OmicsIntegrator-0.3.1/scripts/forest.py", line 1425, in main
    outputObj = PCSFOutput(inputObj,edgeList,info,options.outputpath,options.outputlabel,1)
  File "/opt/OmicsIntegrator-0.3.1/scripts/forest.py", line 757, in __init__
    nx.set_node_attributes(augForest, 'betweenness', betweenness)
  File "/usr/local/lib/python2.7/dist-packages/networkx/classes/function.py", line 654, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'
```

Installing `networkx==1.11` seems to resolve the issue and `forest.py` correctly generates the output files. 

Here is the Dockerfile I used:

```
FROM ubuntu:14.04

LABEL maintainer "gngrbdk@gmail.com"

# Set /opt/ as working directory
WORKDIR /opt

# Copy this file into container
COPY Dockerfile /opt

# Update Ubuntu package index
RUN apt-get update

# Install common dependencies
RUN apt-get install -y \
    wget \
    unzip \
    build-essential \
    software-properties-common \
    libboost-all-dev \
    libxft-dev \
    libfreetype6-dev \
    libblas-dev \
    liblapack-dev \
    libatlas-base-dev \
    gfortran \
    python-pip \
    python-dev \
    python

# Download msgsteiner 1.3
RUN wget http://staff.polito.it/alfredo.braunstein/code/msgsteiner-1.3.tgz && tar xzf msgsteiner-1.3.tgz && rm msgsteiner-1.3.tgz

# Change dir into msgsteiner and compile
WORKDIR /opt/msgsteiner-1.3
RUN make

# Go back to original working directory
WORKDIR /opt

# Download Omics Integrator 0.3.1
RUN wget https://github.com/fraenkel-lab/OmicsIntegrator/archive/v0.3.1.zip && unzip v0.3.1.zip && rm v0.3.1.zip

# Install required Python packages
RUN pip install -r /opt/OmicsIntegrator-0.3.1/requirements.txt

# Download Forest Tuner
RUN wget https://raw.githubusercontent.com/gungorbudak/forest-tuner/master/forest-tuner.py
```

### PR DESCRIPTION
**Pull request by agitter**
Impose a maximum supported networkx version in `requirements.txt`.

Closes #28.

### CODE REVIEW

**Comment by agitter** [comment]
The Travis build [failed](https://travis-ci.org/fraenkel-lab/OmicsIntegrator/builds/342724952).  I'm checking our last build that [passed](https://travis-ci.org/fraenkel-lab/OmicsIntegrator/builds/263509647) to see what else has changed.  SciPy version 0.19.1 was used in the successful build and 1.0.0 was used in the build that failed.

**Comment by agitter** [comment]
This still failed with a max SciPy version.  I believe the error comes from
https://github.com/fraenkel-lab/OmicsIntegrator/blob/10089ee2850a95f808fca7e530e8baea7a947dc9/scripts/motif_regression.py#L101

We're getting divide by 0 errors in SciPy's linregress [here].(https://github.com/scipy/scipy/blob/v0.19.1/scipy/stats/_stats_mstats_common.py#L106-L118)

That's a separate problem, so I'll create a new issue.  Setting a max NumPy version solved the build errors.

**Comment by agitter** [comment]
@AmandaKedaigle @zfrenchee we don't a formal code review policy for this repository, so I plan to merge this in a few days.  Let me know if you have any comments.

**Comment by AmandaKedaigle** [comment]
This looks good to me! Will comment on the other thread about divide by zero errors.

**Pull request merged**
