### PR TITLE
[WIP] Add alpha parameter -- sketch

### PR DESCRIPTION
**Pull request by zfrenchee**
Do not merge. 

This is a sketch to show how you would go about adding the alpha parameter to OmicsIntegrator1. @AmandaKedaigle @iamjli

### CODE REVIEW

**Comment by zfrenchee** [comment]
Please ignore the many-line diff. My text editor automatically removes all trailing whitespace.

**Comment by agitter** [comment]
The Travis failure shows there may be a line wrapping problem: 
```
E     File "/home/travis/build/fraenkel-lab/OmicsIntegrator/scripts/forest.py", line 481
E       degree = Counter({protein1: len(edges.items()) for protein1, edges in self.dirEdges.items()}) +
E                                                                                                     ^
E   SyntaxError: invalid syntax
```

**Comment by zfrenchee** [comment]
@iamjli implemented this himself locally.

**Comment by agitter** [comment]
@zfrenchee can we delete the `add-alpha-parameter` branch?

**Comment by zfrenchee** [comment]
Yup, sorry, my bad@

**Pull request closed without merging**
